@startuml

!theme plain
actor Client #transparent
participant "PeremohaSports" as App
participant "Payment Service" as Payment
participant "AWS SES" as SES
database "DB" as DB
participant "LocalStorage" as LS
hide footbox

Client -> App: 1. openMembershipPage()
activate App
App --> Client: 2. loadMembershipPlans()
deactivate App

Client -> App: 3. selectPlan()
activate App

opt Not logged in
  alt Has an account
    Client -> App: 4. sendCredentials() // and login
    App -> SES: 5. sendOTPRequest()
    activate SES
    SES --> Client: 6. Send OTP
    deactivate SES

  else New user
    Client -> App: 7. sendCredentials() // for further registr if payment ok
    App -> LS: 8.localStorage.setItem()
  end
end


App -> Payment: 9. initiatePayment()
activate Payment
Payment --> App: 10. Payment Status
deactivate Payment

alt Payment Successful
  opt New user
    App -> DB: 11. addNewUser()
    activate DB
    DB --> App: 12. Receipt
    deactivate DB
    SES --> Client: 13. Send OTP
   end

  App -> DB: 14. addUserMembershipPlan()
  activate DB
  DB --> App: 15. Receipt
  deactivate DB
  App --> Client: 16. showPaymentSuccessful()

else Payment Error
  LS --> App: 17. localStorage.clearItem()
  App --> Client: 18. showPaymentError()
  deactivate App
end

destroy App

@enduml
